apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "timed.fullname" . }}-backend
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "timed.name" . }}-backend
data:
  DJANGO_ALLOWED_HOSTS: {{ join "," .Values.ingress.hosts }}
  DJANGO_HOST_DOMAIN: {{ index .Values.ingress.hosts 0 }}
  # TODO should be determine through ingress config
  DJANGO_HOST_PROTOCOL: http
  # TODO sane default guessed by host
  DJANGO_DEFAULT_FROM_EMAIL: {{ .Values.backend.service.emailFrom | quote }}
  DJANGO_SERVER_EMAIL: {{ .Values.backend.service.emailFrom | quote }}
  DJANGO_DATABASE_NAME: {{ .Values.postgresql.postgresDatabase | quote }}
  DJANGO_DATABASE_USER: {{ default "postgres" .Values.postgresql.postgresUser | quote }}
  DJANGO_DATABASE_PORT: {{ .Values.postgresql.service.port | quote }}
{{ if .Values.postgresql.install }}
  DJANGO_DATABASE_HOST: {{ include "timed.postgresql.fullname" . | quote }}
{{ else }}
  DJANGO_DATABASE_HOST: {{ .Values.postgresql.service.host | quote }}
{{ end }}
  DJANGO_ADMIN_USERNAME: {{ .Values.backend.service.adminUsername }}
