apiVersion: batch/v1
kind: Job
metadata:
  # TODO: this should be done during pre phase but to do so following
  # feature is needed: https://github.com/kubernetes/helm/issues/2243
  name: post-upgrade-{{ template "timed.fullname" . }}-dbmigrate
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "timed.name" . }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  activeDeadlineSeconds: 300
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}-dbmigrate
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          env:
            - name: DJANGO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "timed.postgresql.fullname" . }}
                  key: postgres-password
          envFrom:
            - secretRef:
                name: pre-install-{{ template "timed.fullname" . }}-backend
            - configMapRef:
                name: {{ template "timed.fullname" . }}-backend
          command: ["./manage.py", "migrate"]
