apiVersion: v2
name: timed
description: A Helm chart for Kubernetes
type: application
description: Chart for Timed application
version: 0.1.0
appVersion: 1.16.0
keywords:
  - timed
  - tracking
sources:
  - https://github.com/adfinis-sygroup/timed-chart
  - https://github.com/adfinis-sygroup/timed-backend
  - https://github.com/adfinis-sygroup/timed-frontend
maintainers:
  - name: Adfinis SyGroup AG
    email: support@adfinis-sygroup.ch
