{{- if .Values.ingress.enabled -}}
{{- $backendServiceName := print (include "fullname" .) "-backend" -}}
{{- $backendServicePort := .Values.backend.service.externalPort -}}
{{- $frontendServiceName := print (include "fullname" .) "-frontend" -}}
{{- $frontendServicePort := .Values.frontend.service.externalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /admin/
            backend:
              serviceName: {{ $backendServiceName }}
              servicePort: {{ $backendServicePort }}
          - path: /static/
            backend:
              serviceName: {{ $backendServiceName }}
              servicePort: {{ $backendServicePort }}
          - path: /api/
            backend:
              serviceName: {{ $backendServiceName }}
              servicePort: {{ $backendServicePort }}
          # frontend service as catch all backend
          - backend:
              serviceName: {{ $frontendServiceName }}
              servicePort: {{ $frontendServicePort }}
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
