apiVersion: batch/v1
kind: Job
metadata:
  # TODO: this should be done during pre phase but to do so need
  # feature in https://github.com/kubernetes/helm/issues/2243
  name: post-install-{{ template "fullname" . }}-dbmigrate
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "name" . }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  activeDeadlineSeconds: 300
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}-dbmigrate
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          envFrom:
            - secretRef:
                name: pre-install-{{ template "fullname" . }}-backend
            - secretRef:
                name: {{ template "fullname" . }}-backend
            - configMapRef:
                name: {{ template "fullname" . }}-backend
          command: ["./manage.py", "migrate"]
