# This shows a secret as a pre-install hook.
# A pre-install hook is run before the rest of the chart is loaded.
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-backend
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "name" . }}-backend
type: Opaque
data:
  DATABASE_URL: {{ .Values.backend.service.databaseUrl | b64enc | quote }}
